# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_14,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_14 ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then
          rev_base
        else
          "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "cli-0.9.0-2eKe_zUBAQAuGjFuolxsm2SkNyuMVqk4SaYrwzis5jTp";
    path = fetchZigArtifact {
      name = "cli";
      url = "git+https://github.com/sam701/zig-cli#bdaab80c0f24624cb4e8b80bb7b34957263f67b8";
      hash = "sha256-o8p6fEaSJ585MU3v6vwBY0hOvpT2C7Mlo45VWwQwbOE=";
    };
  }
  {
    name = "httpz-0.0.0-PNVzrOu4BgCBCARbwWC7MUn7_MqnGwUNfTXEUryOns06";
    path = fetchZigArtifact {
      name = "httpz";
      url = "git+https://github.com/karlseguin/http.zig#68e760cc9eed0722dfcae69bda0ed9406bb83be2";
      hash = "sha256-vgCsPlVQQ8Ds379bnPWckz7uCP9azkEjzNiR1sGFNqM=";
    };
  }
  {
    name = "ini-0.1.0-YCQ9YsQlAACRplKkaUUXQLWVh2P1VULCsaS4JHhmkJRe";
    path = fetchZigArtifact {
      name = "ini";
      url = "git+https://github.com/ziglibs/ini#30afc2fc875ff817af0ffe490481f6f8aa3b5cd4";
      hash = "sha256-ynzakoLlCH1mKAkMnBa1PG2VMP70dReESVEtZAN6md0=";
    };
  }
  {
    name = "N-V-__8AAHOzAQBh8wB371GN1DXTl1mKs8Rdqj0sJea0U4P7";
    path = fetchZigArtifact {
      name = "metrics";
      url = "https://github.com/karlseguin/metrics.zig/archive/cf2797bcb3aea7e5cdaf4de39c5550c70796e7b1.tar.gz";
      hash = "sha256-948NN050B9w+fXkQbGHB39ex5lPe2FyyFFoLVkKRUkA=";
    };
  }
  {
    name = "wayland-0.4.0-dev-lQa1krLJAQBGO2aKqDcfxUOsW_e4PJZO_K_rxA20RztB";
    path = fetchZigArtifact {
      name = "wayland";
      url = "git+https://codeberg.org/ifreund/zig-wayland#65b01fb69148013eea882c8222a82a1d96a6241b";
      hash = "sha256-G97kemlWXbjIdLYmRUzjg7wmBpR+VbKMOqY3w9w78V8=";
    };
  }
  {
    name = "N-V-__8AAIKCDgB-xcOecIu1Xj1wfMd91LarDfqz7lLranYp";
    path = fetchZigArtifact {
      name = "wayland-protocols";
      url = "git+https://gitlab.freedesktop.org/wayland/wayland-protocols#b3f29d8a41320a9231587835ee5e485f4a5f6eba";
      hash = "sha256-xkB9CYppLgp+cGlqb6teo+jS7qlp7akgIEv4mSdbvvg=";
    };
  }
  {
    name = "websocket-0.1.0-ZPISdXNIAwCXG7oHBj4zc1CfmZcDeyR6hfTEOo8_YI4r";
    path = fetchZigArtifact {
      name = "websocket";
      url = "https://github.com/karlseguin/websocket.zig/archive/7c3f1149bffcde1dec98dea88a442e2b580d750a.tar.gz";
      hash = "sha256-tDnyNptyRxQjrm0MqTmsy2F93yLBYDJE2KkqENJFW4Y=";
    };
  }
  {
    name = "N-V-__8AAKq3AQDAxXNMWRVkNSQxyXYDjTZGuXQFj3G0CwAe";
    path = fetchZigArtifact {
      name = "wlr-protocols";
      url = "git+https://gitlab.freedesktop.org/wlroots/wlr-protocols#a5028afbe4a1cf0daf020c4104c1565a09d6e58a";
      hash = "sha256-m6f7/ES4bK2ZFv8hoxZgUcFNltuRkIctpJuFWAUynkg=";
    };
  }
]
