# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAHOzAQBh8wB371GN1DXTl1mKs8Rdqj0sJea0U4P7";
    path = fetchzip {
      url = "https://github.com/karlseguin/metrics.zig/archive/cf2797bcb3aea7e5cdaf4de39c5550c70796e7b1.tar.gz";
      hash = "sha256-9wb9pU3jTXfZYaQzPuW0IrsftJTyRCJfG9oks6RpKy4=";
    };
  }
  {
    name = "N-V-__8AAIKCDgB-xcOecIu1Xj1wfMd91LarDfqz7lLranYp";
    path = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols";
      rev = "b3f29d8a41320a9231587835ee5e485f4a5f6eba";
      hash = "sha256-xkB9CYppLgp+cGlqb6teo+jS7qlp7akgIEv4mSdbvvg=";
    };
  }
  {
    name = "N-V-__8AAKq3AQDAxXNMWRVkNSQxyXYDjTZGuXQFj3G0CwAe";
    path = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlr-protocols";
      rev = "a5028afbe4a1cf0daf020c4104c1565a09d6e58a";
      hash = "sha256-m6f7/ES4bK2ZFv8hoxZgUcFNltuRkIctpJuFWAUynkg=";
    };
  }
  {
    name = "cli-0.9.0-2eKe_zUBAQAuGjFuolxsm2SkNyuMVqk4SaYrwzis5jTp";
    path = fetchgit {
      url = "https://github.com/sam701/zig-cli";
      rev = "bdaab80c0f24624cb4e8b80bb7b34957263f67b8";
      hash = "sha256-o8p6fEaSJ585MU3v6vwBY0hOvpT2C7Mlo45VWwQwbOE=";
    };
  }
  {
    name = "gobject-0.3.0-Skun7IrmdQHh-PhvmchG9AKnrR2RFS5EhBe5oedb0ITv";
    path = fetchzip {
      url = "https://github.com/ianprime0509/zig-gobject/releases/download/v0.3.0/bindings-gnome47.tar.zst";
      hash = "sha256-yinprQtufl7ojCM2fjz5pcE0A76VqwuAECsSCRyRi3g=";
    };
  }
  {
    name = "httpz-0.0.0-PNVzrOu4BgCBCARbwWC7MUn7_MqnGwUNfTXEUryOns06";
    path = fetchgit {
      url = "https://github.com/karlseguin/http.zig";
      rev = "68e760cc9eed0722dfcae69bda0ed9406bb83be2";
      hash = "sha256-vgCsPlVQQ8Ds379bnPWckz7uCP9azkEjzNiR1sGFNqM=";
    };
  }
  {
    name = "ini-0.1.0-YCQ9YsQlAACRplKkaUUXQLWVh2P1VULCsaS4JHhmkJRe";
    path = fetchgit {
      url = "https://github.com/ziglibs/ini";
      rev = "30afc2fc875ff817af0ffe490481f6f8aa3b5cd4";
      hash = "sha256-ynzakoLlCH1mKAkMnBa1PG2VMP70dReESVEtZAN6md0=";
    };
  }
  {
    name = "wayland-0.4.0-dev-lQa1krLJAQBGO2aKqDcfxUOsW_e4PJZO_K_rxA20RztB";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland";
      rev = "65b01fb69148013eea882c8222a82a1d96a6241b";
      hash = "sha256-G97kemlWXbjIdLYmRUzjg7wmBpR+VbKMOqY3w9w78V8=";
    };
  }
  {
    name = "websocket-0.1.0-ZPISdXNIAwCXG7oHBj4zc1CfmZcDeyR6hfTEOo8_YI4r";
    path = fetchzip {
      url = "https://github.com/karlseguin/websocket.zig/archive/7c3f1149bffcde1dec98dea88a442e2b580d750a.tar.gz";
      hash = "sha256-qyfeyR3Yp5i1YROqaOp4QP8U0rYCXgdeeUKbbXQJMU4=";
    };
  }
]
