# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAIrmDgBCnmm4bZ_KJ9NauVmPd1n7htBPSUi_rQxP";
    path = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols";
      rev = "fff667c829b067500a5a3bf84e7bae1bb293d3aa";
      hash = "sha256-xzmMal4wQx52S4CGOECFutYewOKBZRNASDASSZYaZag=";
    };
  }
  {
    name = "N-V-__8AAMm4AQANnGv8ZhQ9FX_ipu-oul8H7XP9WPD6r5KD";
    path = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlr-protocols";
      rev = "a741f0ac5d655338a5100fc34bc8cec87d237346";
      hash = "sha256-qdimOBtxgrEQDhOWHTWDRVC6p7gl8DjTgtiC+YNLEgs=";
    };
  }
  {
    name = "cli-0.10.0-2eKe_5kEAQBeHqKxUHNTGnETzu81rqKWwT1WPt1jXBt0";
    path = fetchgit {
      url = "https://github.com/sam701/zig-cli";
      rev = "f9a516ddc9771ddd2c8c46a280a9ab6cab8261f2";
      hash = "sha256-gjo2O7jtFcnqbGehwczDOeaRDg7JdUBfu2BcHa+nsH4=";
    };
  }
  {
    name = "gobject-0.3.0-Skun7B3omQB3XhqaKwuLsBMckQrFaNLzBwL5e0j-HNpE";
    path = fetchzip {
      url = "https://github.com/HumXC/mika-shell-gobject/releases/download/latest/bindings.tar.gz";
      hash = "sha256-KnyHbHSsuPCsfq4GlqJw2XoQ936OZN1qtvBO1yFLV10=";
    };
  }
  {
    name = "httpz-0.0.0-PNVzrFe5BgDabt7p2mEiv4PXNOZxJvxR0cMOBtQmP3uR";
    path = fetchgit {
      url = "https://github.com/karlseguin/http.zig";
      rev = "94fc151741af0f8b6962966046743c0726b1ec35";
      hash = "sha256-nhfMScgS0CYDDAbJTKSFIRInyE4wyce4Tn3txPkU4SM=";
    };
  }
  {
    name = "ini-0.1.0-YCQ9YkUnAAA7SjpLwvomwrngMn3TConSAlNgo7Q8ibMZ";
    path = fetchgit {
      url = "https://github.com/ziglibs/ini";
      rev = "bc7809e039148cf7591a1b4a9df28ea9ae879251";
      hash = "sha256-ihTDJUarAFTxrWnyEDmugDNeQdGqEHGcwq5foPsYDO8=";
    };
  }
  {
    name = "metrics-0.0.0-W7G4eP2_AQBKsaql3dhLJ-pkf-RdP-zV3vflJy4N34jC";
    path = fetchzip {
      url = "https://github.com/karlseguin/metrics.zig/archive/13d8706e1ae921a8cc0d2f88283c1b5412c73e2f.tar.gz";
      hash = "sha256-iu19RwA2pIhT+tSwaaLT+9XPNR8Ucaq88XfH9lkeyMk=";
    };
  }
  {
    name = "wayland-0.5.0-dev-lQa1khrMAQDJDwYFKpdH3HizherB7sHo5dKMECfvxQHe";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland";
      rev = "1b5c038ec10da20ed3a15b0b2a6db1c21383e8ea";
      hash = "sha256-1wRkixysjdFMyrATxlXdukAc34MwfNj0B6ydYVn+UKw=";
    };
  }
  {
    name = "websocket-0.1.0-ZPISdYluAwBl2ckLPQ_q5_1IPEmNmaJ9vU1V0ap1-_dD";
    path = fetchzip {
      url = "https://github.com/karlseguin/websocket.zig/archive/59aaa71e64a669aa90016f8a342ceeee6381b4a6.tar.gz";
      hash = "sha256-MDkxGJSoLQ2dQ43Zu4fsqZ7rMOM+10z6PZYsfO/48wk=";
    };
  }
]
