// This file is generated by generate.zig. Do not edit it manually.

export const Mika = {
    "close-request": 0,
    "show-request": 1,
    "hide-request": 2,
    open: 3,
    close: 4,
    show: 5,
    hide: 6,
};
export const Tray = {
    added: 7,
    removed: 8,
    changed: 9,
};
export const Notifd = {
    added: 10,
    removed: 11,
};
export const Dock = {
    changed: 12,
    closed: 13,
    enter: 14,
    leave: 15,
};
export const Libinput = {
    "pointer-motion": 16,
    "pointer-button": 17,
    "keyboard-key": 18,
};
